#include "ImGuiUserData.hpp"

float IMGUI_USER_BLUR_SCALE = 1.0f;
float IMGUI_USER_PLANE_POS[3] = { 0.0f, 0.0f, -2.0f };
float IMGUI_USER_PLANE_ROT[3] = { 0.0f, 0.0f, 0.0f };

IMGUI_USER_BLUR_TYPE IMGUI_USER_BLUR = IMGUI_USER_BLUR_TYPE_FAST;