#pragma once

#include <cstdint>

namespace Render
{

enum DescriptorSetScope
{
    DESCRIPTOR_SET_SCOPE_NONE,
    DESCRIPTOR_SET_SCOPE_MATERIALTEMPLATE,
    DESCRIPTOR_SET_SCOPE_ROOT,
    DESCRIPTOR_SET_SCOPE_RENDERPASS,
    DESCRIPTOR_SET_SCOPE_MATERIALINSTANCE,
    DESCRIPTOR_SET_SCOPE_RENDERITEM
};


}